import type { Effect } from './types';

// The base effect data, without language-specific fields.
export const BASE_EFFECTS: Omit<Effect, 'title' | 'description'>[] = [
  {
    id: 'auto-improve',
    prompt: 'Enhance this photograph by improving its brightness, contrast, saturation, and clarity. The goal is to make the photo look more vibrant and professional while maintaining its photorealistic quality. Do not change the subject or the composition.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'ghibli',
    prompt: 'Transform this photo into the Studio Ghibli animation style. Emphasize soft lighting, lush natural backgrounds, and a painterly, hand-drawn feel.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'headshot',
    prompt: 'Generate a professional, high-quality corporate headshot from this photo. The subject should be wearing professional attire, with a neutral, slightly blurred office background. The lighting should be flattering and even.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'pixel',
    prompt: 'Turn this image into a detailed 16-bit pixel art style. The result should look like a character sprite from a classic SNES RPG.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'hug',
    prompt: 'Combine these two photos. The first is of a person as a kid, the second is the same person as an adult. Create a touching, photorealistic image where the adult is warmly hugging their younger self in a nostalgic, softly lit outdoor setting.',
    imageCount: 2,
    imageLabels: ['Kid Photo', 'Adult Photo'],
  },
  {
    id: 'watercolor',
    prompt: 'Transform this photo into a vibrant watercolor painting. Use soft, blended colors with visible brush strokes and paper texture. The overall feel should be artistic and expressive.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'superhero',
    prompt: 'Redraw this person as a superhero in a dynamic, American comic book art style. Use bold lines, dramatic shading, and a vibrant color palette. Add a simple, abstract energy effect in the background.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'sketch',
    prompt: 'Transform this photo into a detailed pencil sketch. The style should be realistic with clear hatching and cross-hatching for shading. Emphasize the contours and main features of the subject. The background should be a plain white paper texture.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'vintage',
    prompt: 'Apply a vintage 1970s photo effect to this image. The result should have faded colors, a slight sepia tone, increased grain, and subtle light leaks. The overall mood should be nostalgic and warm.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'oil-painting',
    prompt: 'Recreate this photo as a classical oil painting. The style should feature visible, thick brushstrokes (impasto), rich colors, and dramatic lighting reminiscent of the Old Masters. Focus on texture and depth.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'cyberpunk',
    prompt: 'Transform the subject of this photo into a cyberpunk character. Add futuristic clothing, subtle cybernetic enhancements, and place them in a dark, gritty cityscape illuminated by vibrant neon signs and holographic advertisements. The color palette should be dominated by electric blues, pinks, and purples.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'lego',
    prompt: 'Turn the person in this photo into a Lego minifigure. The character should have the classic cylindrical head, blocky torso, and articulated legs. Place the minifigure in a simple scene built entirely from Lego bricks.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'noir',
    prompt: 'Convert this photo into a black and white film noir style. Emphasize high contrast, deep shadows, and dramatic, directional lighting (chiaroscuro). The mood should be mysterious and cinematic.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'pop-art',
    prompt: 'Transform this image into an Andy Warhol-style pop art piece. Use a limited palette of bright, saturated, and contrasting colors. The image should have a strong, graphic quality, similar to a screen print, with simplified details and bold outlines.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'fantasy-elf',
    prompt: 'Reimagine the person in this photo as a fantasy elf. Give them gracefully pointed ears, intricate elven clothing, and maybe subtle fantasy markings. Place them in a magical, ancient forest with dappled sunlight filtering through the canopy.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'steampunk',
    prompt: 'Convert the subject into a steampunk character. Incorporate Victorian-era fashion with mechanical, steam-powered elements like brass goggles, gears, and ornate clockwork devices. The background should be an industrial setting with pipes and steam.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'claymation',
    prompt: 'Transform this image into the style of claymation. The subject should look as if it were sculpted from modeling clay, with visible textures like fingerprints and tool marks. The lighting should be soft, mimicking a stop-motion studio setup.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'stained-glass',
    prompt: 'Redesign this photo as a stained glass window. The image should be composed of distinct, colored glass pieces separated by thick, dark lead lines. The colors should be vibrant and translucent, as if illuminated from behind.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'low-poly',
    prompt: 'Convert this photo into a low-poly 3D art style. The subject and background should be simplified into a mesh of flat, geometric polygons (triangles and quads). Use a clean, minimalist color palette with flat shading.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'golden-hour',
    prompt: 'Relight this photo to simulate the "golden hour" just before sunset. The lighting should be warm, soft, and directional, creating long, gentle shadows. Add a warm, golden tint to the overall image and a slight lens flare effect.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'double-exposure',
    prompt: 'Create a double exposure effect with this photo. Blend the silhouette of the main subject with a scenic image of a dense forest or a sprawling cityscape. The final image should be a seamless and artistic combination of both elements.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'charcoal',
    prompt: 'Recreate this photo as a dramatic charcoal drawing on textured paper. Use a wide range of tones from light grays to deep blacks, with soft, smudged shading and strong, expressive lines.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'impressionist',
    prompt: 'Transform this photo into an Impressionist painting. Emphasize light and color over detail. Use short, thick brushstrokes and a bright, vibrant palette to capture the feeling of a moment in time.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'glitch-art',
    prompt: 'Apply a glitch art effect to this photo. Introduce elements like pixel sorting, datamoshing, scan lines, and RGB color separation (chromatic aberration). The result should look like a corrupted digital file, with a chaotic yet artistic aesthetic.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'origami',
    prompt: 'Recreate this image in an origami style. The subject and scene should appear to be constructed from folded paper, with clear, crisp folds and geometric shapes. Use a simple color palette inspired by colored paper.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'mosaic',
    prompt: 'Transform this photo into a Roman-style mosaic. The image should be made up of small, square tiles (tesserae) of different colors. Maintain the overall composition but simplify the details into the tiled format.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'tattoo',
    prompt: 'Redraw the subject of this photo in a traditional American tattoo flash style. Use bold black outlines, a limited color palette (reds, greens, yellows), and iconic tattoo shading techniques. Place it on a background that looks like aged paper.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'blueprint',
    prompt: 'Convert this photo into an architectural blueprint drawing. The image should be rendered in white lines on a blue background. Simplify the subject into geometric shapes and outlines, adding annotations and measurement lines for a technical look.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'zombie',
    prompt: 'Transform the person in this photo into a zombie. Give them decaying skin, sunken eyes, and tattered clothing. Place them in a post-apocalyptic, deserted urban environment.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'line-art',
    prompt: 'Reduce this photo to minimalist single-line art. Capture the essential contours of the subject with a single, continuous black line on a white background. The style should be elegant, simple, and abstract.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'sand-sculpture',
    prompt: 'Recreate the subject of this photo as a realistic sand sculpture on a sunny beach. The texture should be grainy and sandy, and the sculpture should look detailed yet fragile. The ocean and sky should be visible in the background.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'winter-wonderland',
    prompt: 'Place the subject of the photo into a magical winter wonderland scene. The landscape should be covered in fresh, sparkling snow, with frost on the trees. Add soft, falling snowflakes and a cool, blueish light to the overall image.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'hologram',
    prompt: 'Turn the person in this photo into a glowing, translucent sci-fi hologram. The image should be monochromatic (e.g., blue or green), with visible scan lines and a slight flicker effect. Place the hologram in a dark, futuristic command center.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'storybook',
    prompt: 'Redraw this image in the style of a classic children\'s storybook illustration from the 1950s. Use soft, pastel colors, gentle ink outlines, and a whimsical, friendly tone. The overall feeling should be innocent and charming.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'cubism',
    prompt: 'Reinterpret this photo in a Cubist art style, inspired by Picasso. Deconstruct the subject into geometric forms and depict it from multiple viewpoints simultaneously. The color palette should be muted, using earthy tones.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'ancient-sculpture',
    prompt: 'Transform the subject into a classical Greek or Roman sculpture made of weathered marble. The statue should have realistic anatomy but also show signs of aging, such as cracks, chips, and a patina. Place it on a simple pedestal.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'cel-shaded',
    prompt: 'Apply a cel-shaded (or "toon" shaded) effect to this image, similar to video games like The Legend of Zelda: The Wind Waker. Use flat areas of color for shading, strong black outlines, and a bright, animated aesthetic.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'nebula-portrait',
    prompt: 'Reimagine this person\'s portrait as if their silhouette is a window into a vibrant, colorful nebula. Their form and features should be defined by swirling cosmic gases and shining stars, set against a background of deep space. The final image should be a beautiful and seamless blend of the person and the galaxy.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'woodcut',
    prompt: 'Convert this photo into a traditional woodcut print style. The image should be high-contrast black and white, with strong, rough-hewn lines and textures that mimic carving into a block of wood.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'tiny-planet',
    prompt: 'Transform this landscape photo into a "tiny planet" using a stereographic projection effect. The ground should wrap into a small, spherical shape at the center, with the sky and objects stretching out around it. This is a very abstract transformation.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
  {
    id: 'ufo-sighting',
    prompt: 'Modify this photo to look like a still from a 1960s UFO sighting film. Add a classic, saucer-shaped UFO hovering in the sky. Apply a grainy, black and white, low-fidelity film effect to the entire image.',
    imageCount: 1,
    imageLabels: ['Your Photo'],
  },
];
